name: Test Automation Project

on:
  workflow_dispatch:
    inputs:
      browser:
        type: choice
        description: Choose the browser
        required: true
        options:
         - chrome
         - firefox

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
     - name: Set up JDK 11
       uses: actions/setup-java@v2
       with:
         java-version: '17'
         distribution: 'adopt'
         cache: maven

     - name: Run Regression Tests
       run: mvn test -Dsurefire.suiteXmlFiles=src/main/resources/regression.xml -Dbrowser={{ github.event.inputs.browser }}
